/*INSERT INTO TEAM VALUES ('1', 0);
INSERT INTO TEAM VALUES ('2', 0);
INSERT INTO TEAM VALUES ('3', 0);
INSERT INTO TEAM VALUES ('4', 0);
INSERT INTO TEAM VALUES ('5', 0);
INSERT INTO TEAM VALUES ('6', 0);
INSERT INTO TEAM VALUES ('7', 0);*/